### ISSUE TITLE
apt-cacher-ng server_config value

### ISSUE THREAD

**Issue by RyPeck** [saltstack-formulas/apt-cacher-formula#8]
Why does the `server_config` in the default jinja mapping for `apt-cacher-ng` default to `/etc/apt-cacher-ng/zzz_acng.conf`? Doesn't seem to be a sane config. Shouldn't it be `/etc/apt-cacher-ng/acng.conf`?

https://github.com/saltstack-formulas/apt-cacher-formula/blob/master/apt-cacher/ng/map.jinja#L6

**Comment by gravyboat** [comment]
I'm closing this out @RyPeck Since the PR was already merged. Open it back up if you need to.
